const PERMISSIONS = {
  TICKET_STATUS_CHANGE: "TICKET_STATUS_CHANGE",
  TICKET_ASSIGN: "TICKET_ASSIGN",
  TICKET_WORK_ORDER_CREATE: "TICKET_WORK_ORDER_CREATE",
  TICKET_UPDATE_ADD: "TICKET_UPDATE_ADD",
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  AUDIT_VIEW: "AUDIT_VIEW",
  STAFF_LIST_VIEW: "STAFF_LIST_VIEW",
  ADMIN_ONLY: "ADMIN_ONLY"
};

const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_WORK_ORDER_CREATE,
    PERMISSIONS.TICKET_UPDATE_ADD,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.STAFF_LIST_VIEW,
    PERMISSIONS.ADMIN_ONLY
  ],
  dept_admin: [
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_WORK_ORDER_CREATE,
    PERMISSIONS.TICKET_UPDATE_ADD,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.STAFF_LIST_VIEW
  ],
  staff: [
    PERMISSIONS.TICKET_UPDATE_ADD
  ],
  unknown: []
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
